Cosmetic Data Aquisition Project

Dataset Description

This dataset contains 1,472 cosmetic and skincare products collected from Kaggle. The dataset includes information on product category, brand, product name, price, product rating, ingredients and suitability for different skin types. Initial exploration found no missing values in the dataset. This dataset will be combined with additional information collected from the Ulta Beauty website.

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("cosmetics.csv")

In [4]:
df.head()

,Label,Brand,Name,Price,Rank,Ingredients,Combination,Dry,Normal,Oily,Sensitive
0,Moisturizer,LA MER,Crème de la Mer,175,4.1,"Algae (Seaweed) Extract, Mineral Oil, Petrolat...",1,1,1,1,1
1,Moisturizer,SK-II,Facial Treatment Essence,179,4.1,"Galactomyces Ferment Filtrate (Pitera), Butyle...",1,1,1,1,1
2,Moisturizer,DRUNK ELEPHANT,Protini™ Polypeptide Cream,68,4.4,"Water, Dicaprylyl Carbonate, Glycerin, Ceteary...",1,1,1,1,0
3,Moisturizer,LA MER,The Moisturizing Soft Cream,175,3.8,"Algae (Seaweed) Extract, Cyclopentasiloxane, P...",1,1,1,1,1
4,Moisturizer,IT COSMETICS,Your Skin But Better™ CC+™ Cream with SPF 50+,38,4.1,"Water, Snail Secretion Filtrate, Phenyl Trimet...",1,1,1,1,1

In [5]:
df.shape

(1472, 11)

In [7]:
df.columns

Index(['Label', 'Brand', 'Name', 'Price', 'Rank', 'Ingredients', 'Combination',
       'Dry', 'Normal', 'Oily', 'Sensitive'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1472 entries, 0 to 1471
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Label        1472 non-null   object
 1   Brand        1472 non-null   object
 2   Name         1472 non-null   object
 3   Price        1472 non-null   int64
 4   Rank         1472 non-null   float64
 5   Ingredients  1472 non-null   object
 6   Combination  1472 non-null   int64
 7   Dry          1472 non-null   int64
 8   Normal       1472 non-null   int64
 9   Oily         1472 non-null   int64
 10  Sensitive    1472 non-null   int64
dtypes: float64(1), int64(6), object(4)
memory usage: 126.6+ KB

In [9]:
df.describe()

,Price,Rank,Combination,Dry,Normal,Oily,Sensitive
count,1472.000000,1472.000000,1472.00000,1472.000000,1472.000000,1472.000000,1472.000000
mean,55.584239,4.153261,0.65625,0.614130,0.652174,0.607337,0.513587
std,45.014429,0.633918,0.47512,0.486965,0.476442,0.488509,0.499985
min,3.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,4.000000,0.00000,0.000000,0.000000,0.000000,0.000000
50%,42.500000,4.300000,1.00000,1.000000,1.000000,1.000000,1.000000
75%,68.000000,4.500000,1.00000,1.000000,1.000000,1.000000,1.000000
max,370.000000,5.000000,1.00000,1.000000,1.000000,1.000000,1.000000

In [10]:
df.isnull().sum()

Label          0
Brand          0
Name           0
Price          0
Rank           0
Ingredients    0
Combination    0
Dry            0
Normal         0
Oily           0
Sensitive      0
dtype: int64

Web Scraping Ulta Beauty

To complement the Kaggle Cosmetics Dataset, additional Infornation will be collected from the Ulta Beauty Website. The data extracted will include..... This information will allow the Investigation of whether more popular products receive higher ratings

In [11]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [13]:
url = "https://www.ulta.com/shop/skin-care/all"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print(response.status_code)

200

In [14]:
soup = BeautifulSoup(response.text, "html.parser")

print(soup.title)

<title data-rh="true">Shop All Skin Care - 7291 Products | Ulta Beauty</title>

In [15]:
print(response.text[:1000])

  <!DOCTYPE html>
  <html lang="en-US" class="ULTA_HTML">
    <head>
      <meta charset="utf-8">
      <link rel="icon" href="/favicon.ico">
      <meta name="google-site-verification" content="0iJgVZRwJEqcwh-DfHO3TnKtFasUWdJmJbVBo2j8eg0" />
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <meta name="theme-color" content="#e90b5a">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">

      <meta data-rh="true" name="description" content="Shop all Skin Care products at Ulta Beauty. Free Shipping Offers &amp; Free Store Pickup Available Same Day. Join Ulta Beauty Rewards To Earn Points."/><meta data-rh="true" name="robots" content="index, follow,"/><meta data-rh="true" property="og:title" content="Shop All Skin Care - 7291 Products | Ulta Beauty"/><meta data-rh="true" property="og:description" content="Shop all Skin Care products at Ulta Beauty. Free Shipping Offers &amp; Free Store Pickup Available Same Day. Join ULTAmate Rewards To Earn P